name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run backend tests
      working-directory: ./backend
      env:
        GOOGLE_API_KEY: "test-key"
      run: |
        pytest tests/ -m "not ai_real" -v --tb=short
        
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false
      
    - name: Run frontend linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Run integration tests
      run: |
        # Start backend
        cd backend && uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        
        # Test backend
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/todos || exit 1
        
        # Test frontend build
        test -d frontend/.next || exit 1
        
        # Cleanup
        pkill -f uvicorn || true
        
    - name: Run AI tests (real) - Optional
      working-directory: ./backend
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        pytest tests/test_ai_real.py -m "ai_real" -v --tb=short
      
    - name: Generate test report
      run: |
        echo "=== Test Summary ==="
        echo "✅ Backend tests: Passed"
        echo "✅ Frontend tests: Passed"
        echo "✅ Integration tests: Passed"
        echo "✅ AI mock tests: Passed"
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ AI real tests: Passed (Google API)"
        else
          echo "⚠️ AI real tests: Skipped (no Google API key)"
        fi
        echo "🎉 All tests completed!"
